//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using OrganWeb.Areas.Sistema.Models.Semente;
    
    public partial class dborganwebEntities : DbContext
    {
        public dborganwebEntities()
            : base("name=dborganwebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbsemente> Sementes { get; set; }
    }
}
